"""add charge table

Revision ID: 002ff4642c09
Revises: eb3f0e5e413d
Create Date: 2026-07-03 00:32:15.290873
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '002ff4642c09'
down_revision: str | None = 'eb3f0e5e413d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('phase_record_id', sa.Uuid(), nullable=False),
    sa.Column('billing_code_id', sa.Uuid(), nullable=True),
    sa.Column('payer_code_rule_id', sa.Uuid(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnosis_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('charge_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('coded', 'needs_review', name='chargestatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_code_id'], ['billing_code.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_code_rule_id'], ['payer_code_rule.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_record_id'], ['phase_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_billing_code_id'), 'charge', ['billing_code_id'], unique=False)
    op.create_index(op.f('ix_charge_payer_code_rule_id'), 'charge', ['payer_code_rule_id'], unique=False)
    op.create_index(op.f('ix_charge_phase_record_id'), 'charge', ['phase_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charge_phase_record_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_payer_code_rule_id'), table_name='charge')
    op.drop_index(op.f('ix_charge_billing_code_id'), table_name='charge')
    op.drop_table('charge')
    # ### end Alembic commands ###
