"""add intake_raw_record.flags

Revision ID: 438f6ce85448
Revises: 60fda85506a5
Create Date: 2026-07-02 14:17:17.018460
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '438f6ce85448'
down_revision: str | None = '60fda85506a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any existing rows with an empty list so the
    # NOT NULL add is safe; the app supplies the default going forward.
    op.add_column(
        "intake_raw_record",
        sa.Column(
            "flags",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )
    op.alter_column("intake_raw_record", "flags", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_raw_record', 'flags')
    # ### end Alembic commands ###
