"""initial schema

Revision ID: 60fda85506a5
Revises: 
Create Date: 2026-07-02 13:33:53.119166
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60fda85506a5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_code',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('phase', sa.Enum('screening', 'preparation', 'administration', 'monitoring', 'integration', name='phase', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('modality', sa.Enum('psilocybin', name='modality', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_billing_code_code')
    )
    op.create_index(op.f('ix_billing_code_phase'), 'billing_code', ['phase'], unique=False)
    op.create_table('clinic',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_system', sa.Enum('homecoming', 'althea', 'manual', name='sourcesystem', native_enum=False, length=32), nullable=False),
    sa.Column('baa_status', sa.Enum('pending', 'signed', 'expired', name='baastatus', native_enum=False, length=32), nullable=False),
    sa.Column('baa_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payer',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('medicaid', 'commercial', name='payertype', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_id'], ['payer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_clinic_id'), 'client', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_client_payer_id'), 'client', ['payer_id'], unique=False)
    op.create_table('clinician',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credential_type', sa.String(length=64), nullable=True),
    sa.Column('npi', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinician_clinic_id'), 'clinician', ['clinic_id'], unique=False)
    op.create_index(op.f('ix_clinician_npi'), 'clinician', ['npi'], unique=False)
    op.create_table('intake_batch',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.Enum('homecoming', 'althea', 'manual', name='sourcesystem', native_enum=False, length=32), nullable=False),
    sa.Column('import_type', sa.Enum('csv', 'pdf', 'manual', name='importtype', native_enum=False, length=32), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_file_ref', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_batch_clinic_id'), 'intake_batch', ['clinic_id'], unique=False)
    op.create_table('payer_code_rule',
    sa.Column('payer_id', sa.Uuid(), nullable=False),
    sa.Column('billing_code_id', sa.Uuid(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_code_id'], ['billing_code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['payer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payer_code_rule_billing_code_id'), 'payer_code_rule', ['billing_code_id'], unique=False)
    op.create_index(op.f('ix_payer_code_rule_payer_id'), 'payer_code_rule', ['payer_id'], unique=False)
    op.create_table('documentation_requirement',
    sa.Column('payer_code_rule_id', sa.Uuid(), nullable=False),
    sa.Column('required_field', sa.String(length=128), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payer_code_rule_id'], ['payer_code_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentation_requirement_payer_code_rule_id'), 'documentation_requirement', ['payer_code_rule_id'], unique=False)
    op.create_table('episode_of_care',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('modality', sa.Enum('psilocybin', name='modality', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_of_care_client_id'), 'episode_of_care', ['client_id'], unique=False)
    op.create_table('phase_record',
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('clinician_id', sa.Uuid(), nullable=True),
    sa.Column('phase', sa.Enum('screening', 'preparation', 'administration', 'monitoring', 'integration', name='phase', native_enum=False, length=32), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('documented', 'incomplete', 'ready_to_code', name='phasestatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['clinician.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode_of_care.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phase_record_clinician_id'), 'phase_record', ['clinician_id'], unique=False)
    op.create_index(op.f('ix_phase_record_episode_id'), 'phase_record', ['episode_id'], unique=False)
    op.create_index(op.f('ix_phase_record_phase'), 'phase_record', ['phase'], unique=False)
    op.create_table('documentation_record',
    sa.Column('phase_record_id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_notes', sa.Text(), nullable=True),
    sa.Column('vitals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_in_session_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['phase_record_id'], ['phase_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentation_record_phase_record_id'), 'documentation_record', ['phase_record_id'], unique=True)
    op.create_table('intake_raw_record',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalization_status', sa.Enum('pending', 'normalized', 'flagged_incomplete', name='normalizationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('phase_record_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['intake_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_record_id'], ['phase_record.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intake_raw_record_batch_id'), 'intake_raw_record', ['batch_id'], unique=False)
    op.create_index(op.f('ix_intake_raw_record_phase_record_id'), 'intake_raw_record', ['phase_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_raw_record_phase_record_id'), table_name='intake_raw_record')
    op.drop_index(op.f('ix_intake_raw_record_batch_id'), table_name='intake_raw_record')
    op.drop_table('intake_raw_record')
    op.drop_index(op.f('ix_documentation_record_phase_record_id'), table_name='documentation_record')
    op.drop_table('documentation_record')
    op.drop_index(op.f('ix_phase_record_phase'), table_name='phase_record')
    op.drop_index(op.f('ix_phase_record_episode_id'), table_name='phase_record')
    op.drop_index(op.f('ix_phase_record_clinician_id'), table_name='phase_record')
    op.drop_table('phase_record')
    op.drop_index(op.f('ix_episode_of_care_client_id'), table_name='episode_of_care')
    op.drop_table('episode_of_care')
    op.drop_index(op.f('ix_documentation_requirement_payer_code_rule_id'), table_name='documentation_requirement')
    op.drop_table('documentation_requirement')
    op.drop_index(op.f('ix_payer_code_rule_payer_id'), table_name='payer_code_rule')
    op.drop_index(op.f('ix_payer_code_rule_billing_code_id'), table_name='payer_code_rule')
    op.drop_table('payer_code_rule')
    op.drop_index(op.f('ix_intake_batch_clinic_id'), table_name='intake_batch')
    op.drop_table('intake_batch')
    op.drop_index(op.f('ix_clinician_npi'), table_name='clinician')
    op.drop_index(op.f('ix_clinician_clinic_id'), table_name='clinician')
    op.drop_table('clinician')
    op.drop_index(op.f('ix_client_payer_id'), table_name='client')
    op.drop_index(op.f('ix_client_clinic_id'), table_name='client')
    op.drop_table('client')
    op.drop_table('payer')
    op.drop_table('clinic')
    op.drop_index(op.f('ix_billing_code_phase'), table_name='billing_code')
    op.drop_table('billing_code')
    # ### end Alembic commands ###
