"""add remittance

Revision ID: 9ee440614034
Revises: b534a9c31ff0
Create Date: 2026-07-03 00:43:29.044323
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ee440614034'
down_revision: str | None = 'b534a9c31ff0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittance',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('paid', 'denied', name='remittancestatus', native_enum=False, length=32), nullable=False),
    sa.Column('charged_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('underpaid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('adjustments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('denial_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_835', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['payer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remittance_claim_id'), 'remittance', ['claim_id'], unique=True)
    op.create_index(op.f('ix_remittance_payer_id'), 'remittance', ['payer_id'], unique=False)
    op.create_index(op.f('ix_remittance_status'), 'remittance', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remittance_status'), table_name='remittance')
    op.drop_index(op.f('ix_remittance_payer_id'), table_name='remittance')
    op.drop_index(op.f('ix_remittance_claim_id'), table_name='remittance')
    op.drop_table('remittance')
    # ### end Alembic commands ###
