"""add claim table and charge.claim_id

Revision ID: b534a9c31ff0
Revises: 002ff4642c09
Create Date: 2026-07-03 00:37:37.345144
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b534a9c31ff0'
down_revision: str | None = '002ff4642c09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=True),
    sa.Column('episode_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scrubbed', 'submitted', 'accepted', 'rejected', 'paid', 'denied', name='claimstatus', native_enum=False, length=32), nullable=False),
    sa.Column('control_number', sa.String(length=32), nullable=True),
    sa.Column('total_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scrub_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_837', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['episode_id'], ['episode_of_care.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['payer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_client_id'), 'claim', ['client_id'], unique=False)
    op.create_index(op.f('ix_claim_episode_id'), 'claim', ['episode_id'], unique=False)
    op.create_index(op.f('ix_claim_payer_id'), 'claim', ['payer_id'], unique=False)
    op.create_index(op.f('ix_claim_status'), 'claim', ['status'], unique=False)
    op.add_column('charge', sa.Column('claim_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_charge_claim_id'), 'charge', ['claim_id'], unique=False)
    op.create_foreign_key(
        'fk_charge_claim_id', 'charge', 'claim', ['claim_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_charge_claim_id', 'charge', type_='foreignkey')
    op.drop_index(op.f('ix_charge_claim_id'), table_name='charge')
    op.drop_column('charge', 'claim_id')
    op.drop_index(op.f('ix_claim_status'), table_name='claim')
    op.drop_index(op.f('ix_claim_payer_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_episode_id'), table_name='claim')
    op.drop_index(op.f('ix_claim_client_id'), table_name='claim')
    op.drop_table('claim')
    # ### end Alembic commands ###
