"""add eligibility_check

Revision ID: eb3f0e5e413d
Revises: 438f6ce85448
Create Date: 2026-07-02 14:24:36.264430
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb3f0e5e413d'
down_revision: str | None = '438f6ce85448'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_check',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('payer_id', sa.Uuid(), nullable=True),
    sa.Column('service_type_code', sa.String(length=16), nullable=False),
    sa.Column('subscriber_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'needs_info', 'not_found', 'error', name='eligibilitystatus', native_enum=False, length=32), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gateway', sa.String(length=32), nullable=False),
    sa.Column('coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payer_id'], ['payer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_check_client_id'), 'eligibility_check', ['client_id'], unique=False)
    op.create_index(op.f('ix_eligibility_check_payer_id'), 'eligibility_check', ['payer_id'], unique=False)
    op.create_index(op.f('ix_eligibility_check_status'), 'eligibility_check', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eligibility_check_status'), table_name='eligibility_check')
    op.drop_index(op.f('ix_eligibility_check_payer_id'), table_name='eligibility_check')
    op.drop_index(op.f('ix_eligibility_check_client_id'), table_name='eligibility_check')
    op.drop_table('eligibility_check')
    # ### end Alembic commands ###
